### ISSUE TITLE
Convert agent created context to root agent context

### ISSUE THREAD

**Issue by guillemcordoba** [uprtcl/hc-uprtcl#7]

**Comment by JoseOspina** [comment]
HI @guillemcordoba, [this is what I was thinking](https://www.collectiveone.org/#/app/inits/ac12cace-66f9-1475-8166-fcda2a0e0001/model/section/ac12e2ee-6a35-1d43-816a-364fc42e0339/cards/ac12c992-6a5f-100b-816a-646a50cf0023) regarding the agent root context:
